### ISSUE TITLE
Have you looked at using PiServer to manage the Raspberry PIs

### ISSUE THREAD

**Issue by wpbest** [mhurd/kubernetes#1]
Have you looked at using PiServer to manage the Raspberry PI nodes?

With PiServer, you don’t need SD cards, you can control all nodes via the server.
the Raspberry Pi 3 Model B can be booted without an SD card over an Ethernet network from another computer (the server). This is called network booting or PXE (pronounced ‘pixie’) booting.
It is possible to use PiServer to develop a network of Raspberry Pis (maybe even using Power over Ethernet (PoE)) such that the control software for each Pi is stored remotely on a server. This enables easy remote control and provisioning of the Pis from a central repository.
https://www.raspberrypi.org/blog/piserver/

**Comment by mhurd** [comment]
Thanks for the heads up @wpbest, I'll take a look.
